version: '3.8'
services:
  app:
    container_name: hospitalityhub
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://root:example@db:27017/
      - TOKEN=trbjhJ5qDQdhovRHxaAasz8esSSGMAtGizEAeuAep55zwsPL4nPePr5iAdwUPTVjLfiLZqrNfejwC9VPoWUvg9QBvZahes7NefBAt7tRzUcPFWPHuCR88A6EshmkEWt3
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
volumes:
  db-data:
  src: